### ISSUE TITLE
Improvement: Unused styles

### ISSUE THREAD

**Issue by Danielduel** [brewek/czymoznawyjsczdomu.pl#1]
```
  p {
    margin: 1em auto;
    text-align: center;
  }
  
  div.footer {
    position: fixed;
    bottom: 0;
    width: 100%;
    margin: 1em auto;
    text-align: center;
  }
```

Is unused, pleaz remove

**Comment by brewek** [comment]
Thank you very much for your feedback.

Your issue has now been resolved and incorporated into the source code.

Thank you for helping us create a better Tomorrow with more robust code.

God bless you.

**Comment by Danielduel** [comment]
No problemo maj friend, I am always hir to sejw da day. Awesome reaction time.
