### ISSUE TITLE
Status is not aligned to center

### ISSUE THREAD

**Issue by kgruszka** [brewek/czymoznawyjsczdomu.pl#2]
The status on the page is not aligned to the center but slightly shifted to the right side.

System: macOS Mojave Version 10.14.6
Browser: Chrome Version 85.0.4183.121 (Official Build) (64-bit)

![Screenshot 2020-10-06 at 12 18 53](https://user-images.githubusercontent.com/8074860/95189707-7f941280-07ce-11eb-8f99-1924e4edba2c.png)

**Comment by krolpawel** [comment]
Fixed in https://github.com/brewek/czymoznawyjsczdomu.pl/pull/3
